blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/yen0304/pretok/discussions
    about: Ask questions and discuss ideas
  - name: PyPI Package
    url: https://pypi.org/project/pretok/
    about: View package on PyPI
